name: Publish to npm

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (latest, beta, alpha)'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
          - alpha

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Verify package contents
        run: |
          npm pack --dry-run
          echo "Package size:"
          du -sh *.tgz 2>/dev/null || echo "No tarball found (dry-run)"

      - name: Publish to npm (latest)
        if: github.event_name == 'release' || github.event.inputs.tag == 'latest'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm (beta)
        if: github.event.inputs.tag == 'beta'
        run: npm publish --tag beta --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm (alpha)
        if: github.event.inputs.tag == 'alpha'
        run: npm publish --tag alpha --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release Summary
        run: |
          echo "## 📦 Package Published to npm" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Package:** @vue-tdd/automation" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** $(node -p "require('./package.json').version")" >> $GITHUB_STEP_SUMMARY
          echo "**Tag:** ${{ github.event.inputs.tag || 'latest' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event.inputs.tag }}" == "latest" ] || [ "${{ github.event_name }}" == "release" ]; then
            echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
            echo "npm install @vue-tdd/automation" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
            echo "npm install @vue-tdd/automation@${{ github.event.inputs.tag }}" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi
